### ISSUE TITLE
phase offset on 40MHZ bandwidth?

### ISSUE THREAD

**Issue by Captital123** [zhangdh24/Calibrating-Phase-Offsets-for-Commodity-WiFi#1]
@zhangdh24  Many research concerning indoor positioning uses 40MHZ channel bandwidth, such as “Spotfi” and "Lgtm". you give the phase offset measured under 20MHZ bandwidth in the article "Calibrating Phase Offsets for Commodity WiFi" TABLE.1.  May I ask whether you have conducted the same experiment under 40MHZ bandwidth? Is it convenient to share the phase offset under 40MHZ?

**Comment by zhangdh24** [comment]
The experiments are conducted under 40MHz channel bandwidth
